import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import SmallCard from "@/components/SmallCard";
import MediumCard from "@/components/MediumCard";
import LargeCard from "@/components/LargeCard";
import Footer from "@/components/Footer";
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home({ exploreData, CardData }) {
  return (
    <>
      <Head>
        <title>Nikhil airbnb Next </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Header />
        <Banner />
        <main className=" m-w-7xl mx-auto px-8 sm:px-16">
          <section className="pt-6">
            <h2 className="font-semibold text-4xl pb-5">Explore Nearby</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {exploreData?.map(({ image, location, distance }) => (
                <SmallCard
                  key={image}
                  image={image}
                  location={location}
                  distance={distance}
                />
              ))}
            </div>
          </section>

          <section className="pt-6">
            <h2 className="font-semibold text-4xl pb-5"> Live anywhere</h2>
            <div className="flex gap-4  overflow-scroll scrollbar-hide p-3 ">
              {CardData?.map(({ image, title }) => (
                <MediumCard key={image} image={image} title={title} />
              ))}
            </div>
          </section>

          <LargeCard
            image={"https://links.papareact.com/4cj"}
            title={"The greate soutdoors"}
            description={"whishlist curated by airbnb"}
            buttonText={"Get Inspired"}
          />
        </main>

        <Footer/>
        
      </div>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(
    "https://airbnb-5be6a-default-rtdb.firebaseio.com/Smallcard.json"
  ).then((res) => res.json());
  const CardData = await fetch(
    "https://airbnb-5be6a-default-rtdb.firebaseio.com/MediumCard.json"
  ).then((res) => res.json());
  return {
    props: {
      exploreData,
      CardData,
    },
  };
}
